import { Activity, ArrowLeft, Database, Flag, Gauge, Search, Settings, Shield, ToggleLeft, ToggleRight, Users, Workflow } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { request } from '../api/client';
import type { AdminOverview, AdminUser, AdminWorkspace, FeatureFlag, HealthSnapshot, SystemSetting } from '../admin';

type Tab='overview'|'users'|'workspaces'|'flags'|'settings'|'health';
export default function AdminPage({onBack}:{onBack:()=>void}){
 const [tab,setTab]=useState<Tab>('overview'); const [overview,setOverview]=useState<AdminOverview>(); const [users,setUsers]=useState<AdminUser[]>([]);
 const [workspaces,setWorkspaces]=useState<AdminWorkspace[]>([]); const [flags,setFlags]=useState<FeatureFlag[]>([]); const [settings,setSettings]=useState<SystemSetting[]>([]); const [health,setHealth]=useState<HealthSnapshot>();
 const [search,setSearch]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const [o,u,w,f,s,h]=await Promise.all([request<AdminOverview>('/admin/overview'),request<AdminUser[]>('/admin/users'),request<AdminWorkspace[]>('/admin/workspaces'),request<FeatureFlag[]>('/admin/feature-flags'),request<SystemSetting[]>('/admin/settings'),request<HealthSnapshot>('/admin/health')]);setOverview(o);setUsers(u);setWorkspaces(w);setFlags(f);setSettings(s);setHealth(h)}catch(e){setError(e instanceof Error?e.message:'Admin data could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>users.filter(x=>`${x.displayName} ${x.email}`.toLowerCase().includes(search.toLowerCase())),[users,search]);
 async function role(user:AdminUser,value:AdminUser['role']){const updated=await request<AdminUser>(`/admin/users/${user.id}/role`,{method:'PUT',body:JSON.stringify({role:value})});setUsers(v=>v.map(x=>x.id===updated.id?updated:x))}
 async function status(user:AdminUser){const updated=await request<AdminUser>(`/admin/users/${user.id}/status`,{method:'PUT',body:JSON.stringify({isActive:!user.isActive})});setUsers(v=>v.map(x=>x.id===updated.id?updated:x))}
 async function toggle(flag:FeatureFlag){const updated=await request<FeatureFlag>(`/admin/feature-flags/${flag.id}`,{method:'PUT',body:JSON.stringify({isEnabled:!flag.isEnabled})});setFlags(v=>v.map(x=>x.id===updated.id?updated:x))}
 const tabs:[Tab,string,React.ElementType][]=[['overview','Overview',Gauge],['users','Users',Users],['workspaces','Workspaces',Workflow],['flags','Feature flags',Flag],['settings','Settings',Settings],['health','Health',Activity]];
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="brand"><Shield size={20}/>Admin Console</div><button className="admin-back" onClick={onBack}><ArrowLeft size={16}/>Back to workspace</button><nav>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</nav><div className="admin-scope">ADMIN ONLY<span>Role-protected API</span></div></aside><section className="admin-content"><header><div><p className="eyebrow">Platform administration</p><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><button className="secondary" onClick={()=>void load()}>Refresh data</button></header>{error&&<div className="admin-error">{error}</div>}{loading?<div className="admin-loading">Loading administration data…</div>:<>
 {tab==='overview'&&overview&&<><section className="admin-kpis"><Kpi label="Total users" value={overview.totalUsers} hint={`${overview.activeUsers} active`} icon={Users}/><Kpi label="Workspaces" value={overview.workspaces} hint="Across the platform" icon={Workflow}/><Kpi label="Open incidents" value={overview.openIncidents} hint="Needs attention" icon={Shield}/><Kpi label="Failed pipelines" value={overview.failedPipelines} hint="Current history" icon={Activity}/></section><section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">Audit trail</p><h2>Recent administrative activity</h2></div><span>{overview.unreadNotifications} unread notifications</span></div><div className="activity-list">{overview.recentActivity.map(x=><div key={x.id}><span className="activity-dot"/><div><strong>{x.action} · {x.entityType}</strong><small>{x.userEmail||'System'} · {new Date(x.createdAtUtc).toLocaleString()}</small></div></div>)}</div></section></>}
 {tab==='users'&&<section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">Identity management</p><h2>Users and access</h2></div><label className="admin-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search users"/></label></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last login</th><th>Action</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><strong>{u.displayName}</strong><small>{u.email}</small></td><td><select value={u.role} onChange={e=>void role(u,e.target.value as AdminUser['role'])}><option>Admin</option><option>Owner</option><option>Member</option></select></td><td><span className={u.isActive?'pill ok':'pill off'}>{u.isActive?'Active':'Suspended'}</span></td><td>{u.lastLoginAtUtc?new Date(u.lastLoginAtUtc).toLocaleDateString():'Never'}</td><td><button className="row-action" onClick={()=>void status(u)}>{u.isActive?'Suspend':'Activate'}</button></td></tr>)}</tbody></table></div></section>}
 {tab==='workspaces'&&<section className="admin-grid-list">{workspaces.map(w=><article className="admin-workspace" key={w.id}><div className="workspace-icon"><Workflow size={18}/></div><div><strong>{w.name}</strong><span>/{w.slug}</span></div><div className="workspace-stats"><b>{w.members}</b><small>members</small><b>{w.projects}</b><small>projects</small></div></article>)}</section>}
 {tab==='flags'&&<section className="admin-grid-list">{flags.map(f=><article className="flag-card" key={f.id}><div><p className="eyebrow">{f.key}</p><h3>{f.description}</h3></div><button className={f.isEnabled?'flag-toggle on':'flag-toggle'} onClick={()=>void toggle(f)}>{f.isEnabled?<ToggleRight size={34}/>:<ToggleLeft size={34}/>}<span>{f.isEnabled?'Enabled':'Disabled'}</span></button></article>)}</section>}
 {tab==='settings'&&<section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">Runtime configuration</p><h2>System settings</h2></div></div><div className="settings-list">{settings.map(s=><div key={s.id}><div><strong>{s.key}</strong><span>{s.category}</span></div><code>{s.value}</code></div>)}</div></section>}
 {tab==='health'&&health&&<section className="health-grid"><article><Database size={26}/><span>API</span><strong>{health.api}</strong></article><article><Database size={26}/><span>Database</span><strong>{health.database}</strong></article><article><Activity size={26}/><span>Logs / 24h</span><strong>{health.logsLast24Hours}</strong></article><article><Shield size={26}/><span>Errors / 24h</span><strong>{health.errorsLast24Hours}</strong></article><article className="span-two"><Database size={26}/><span>SQLite size</span><strong>{(health.databaseSizeBytes/1024).toFixed(1)} KB</strong><small>Checked {new Date(health.checkedAtUtc).toLocaleString()}</small></article></section>}
 </>}</section></main>
}
function Kpi({label,value,hint,icon:Icon}:{label:string;value:number;hint:string;icon:React.ElementType}){return <article><div><span>{label}</span><Icon size={19}/></div><strong>{value}</strong><small>{hint}</small></article>}
