import { FormEvent, useEffect, useMemo, useState } from 'react';
import { BookOpen, Clock3, FileText, Plus, Search, Star, X } from 'lucide-react';
import { request } from '../api/client';
import type { WikiDocument, WikiDocumentList, WikiSpace, WorkspaceSummary } from '../documentation/types';

export default function DocumentationPage({onBack}:{onBack:()=>void}) {
  const [workspace,setWorkspace]=useState<WorkspaceSummary|null>(null); const [space,setSpace]=useState<WikiSpace|null>(null);
  const [documents,setDocuments]=useState<WikiDocumentList[]>([]); const [selected,setSelected]=useState<WikiDocument|null>(null);
  const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [favorites,setFavorites]=useState(false); const [editing,setEditing]=useState(false); const [error,setError]=useState('');
  async function bootstrap(){const workspaces=await request<WorkspaceSummary[]>('/workspaces'); const first=workspaces[0]; if(!first)return; setWorkspace(first); const spaces=await request<WikiSpace[]>(`/documentation/spaces/${first.id}`); setSpace(spaces[0]??null); await load(first.id);}
  async function load(workspaceId=workspace?.id){if(!workspaceId)return; const p=new URLSearchParams({workspaceId,query,category:category==='All'?'':category,favoritesOnly:String(favorites)}); const docs=await request<WikiDocumentList[]>(`/documentation/documents?${p}`); setDocuments(docs); if(!selected&&docs[0]) await open(docs[0].id);}
  async function open(id:string){setSelected(await request<WikiDocument>(`/documentation/documents/${id}`)); setEditing(false)}
  useEffect(()=>{bootstrap().catch(e=>setError(e.message))},[]); useEffect(()=>{if(workspace)load().catch(e=>setError(e.message))},[query,category,favorites]);
  const categories=useMemo(()=>['All',...Array.from(new Set(documents.map(x=>x.category)))],[documents]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const updated=await request<WikiDocument>(`/documentation/documents/${selected.id}`,{method:'PUT',body:JSON.stringify({title:f.get('title'),content:f.get('content'),category:f.get('category')})});setSelected(updated);setEditing(false);await load();}
  async function create(){if(!space)return;const doc=await request<WikiDocument>('/documentation/documents',{method:'POST',body:JSON.stringify({wikiSpaceId:space.id,title:'Untitled document',content:'# Untitled document\n\nStart writing here.',category:'General'})});await load();await open(doc.id);setEditing(true)}
  async function toggleFavorite(){if(!selected)return;await request(`/documentation/documents/${selected.id}/favorite`,{method:'POST'});setSelected({...selected,isFavorite:!selected.isFavorite});await load()}
  return <div className="docs-shell"><header className="topbar"><button className="ghost" onClick={onBack}>← Dashboard</button><div><b>Documentation</b><span>Runbooks, ADRs and engineering standards</span></div><button className="primary" onClick={create}><Plus size={16}/> New document</button></header>{error&&<div className="error-banner">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}
  <main className="docs-layout"><aside className="docs-sidebar"><div className="docs-space"><BookOpen/><div><strong>{space?.name??'Engineering Wiki'}</strong><span>{space?.documentCount??0} documents</span></div></div><div className="search"><Search size={16}/><input placeholder="Search documentation" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className={`favorite-filter ${favorites?'active':''}`} onClick={()=>setFavorites(!favorites)}><Star size={15}/> Favorites</button><div className="docs-categories">{categories.map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div></aside>
  <section className="docs-list"><div className="section-head compact"><div><h2>Documents</h2><p>{documents.length} results</p></div></div>{documents.map(d=><button key={d.id} className={`doc-row ${selected?.id===d.id?'active':''}`} onClick={()=>open(d.id)}><FileText size={18}/><div><strong>{d.title}</strong><span>{d.category} · {new Date(d.updatedAtUtc).toLocaleDateString('tr-TR')}</span></div>{d.isFavorite&&<Star size={14} fill="currentColor"/>}</button>)}</section>
  <section className="doc-view">{selected? editing?<form className="doc-editor" onSubmit={save}><div className="editor-actions"><button type="button" className="ghost" onClick={()=>setEditing(false)}>Cancel</button><button className="primary">Save revision</button></div><input name="title" defaultValue={selected.title} className="title-input"/><input name="category" defaultValue={selected.category}/><textarea name="content" defaultValue={selected.content}/></form>:<><div className="doc-toolbar"><span className="tag">{selected.category}</span><div><button className="icon-button" onClick={toggleFavorite}><Star size={17} fill={selected.isFavorite?'currentColor':'none'}/></button><button className="secondary" onClick={()=>setEditing(true)}>Edit</button></div></div><article className="markdown-preview"><h1>{selected.title}</h1>{selected.content.split('\n').map((line,i)=>line.startsWith('## ')?<h2 key={i}>{line.slice(3)}</h2>:line.startsWith('# ')?null:line.startsWith('- ')?<li key={i}>{line.slice(2)}</li>:line.match(/^\d+\. /)?<li key={i}>{line.replace(/^\d+\. /,'')}</li>:line?<p key={i}>{line}</p>:<br key={i}/>)}</article><div className="revision-panel"><h3><Clock3 size={16}/> Revision history</h3>{selected.revisions.length===0?<p>No previous revisions.</p>:selected.revisions.map(r=><div key={r.id}><strong>{r.title}</strong><span>{new Date(r.createdAtUtc).toLocaleString('tr-TR')}</span></div>)}</div></>:<div className="empty-state"><FileText size={40}/><h2>Select a document</h2></div>}</section></main></div>
}
