import { Activity, AlertTriangle, ArrowLeft, CheckCircle2, Clock3, Gauge, Plus, Server, ShieldAlert, TimerReset, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { Incident, IncidentDashboard, IncidentSeverity } from '../incidents/types';

const seed:IncidentDashboard={activeIncidents:2,sev1Count:0,mttaMinutes:7.4,mttrMinutes:42.8,slaCompliancePercent:96.7,services:[
{id:'1',name:'Public API',slug:'public-api',description:'Customer-facing REST API',status:'Degraded',availabilityPercent:99.94,targetSlaMinutes:45,openIncidentCount:1},
{id:'2',name:'Identity',slug:'identity',description:'Authentication and token service',status:'Operational',availabilityPercent:99.99,targetSlaMinutes:30,openIncidentCount:0},
{id:'3',name:'Web Application',slug:'web-app',description:'Primary customer dashboard',status:'Operational',availabilityPercent:99.97,targetSlaMinutes:60,openIncidentCount:0},
{id:'4',name:'Build Runners',slug:'build-runners',description:'CI execution workers',status:'PartialOutage',availabilityPercent:99.81,targetSlaMinutes:90,openIncidentCount:1}],incidents:[
{id:'a',number:1042,title:'Elevated API latency in EU region',summary:'P95 latency exceeded 2.5 seconds for write endpoints.',severity:'Sev2',status:'Identified',commander:'Elif Kaya',startedAtUtc:new Date(Date.now()-38*60000).toISOString(),slaDueAtUtc:new Date(Date.now()+7*60000).toISOString(),isSlaBreached:false,serviceName:'Public API',updates:[{id:'u2',status:'Identified',message:'Connection pool saturation identified. Capacity increased while root cause is investigated.',author:'Mert Demir',createdAtUtc:new Date(Date.now()-16*60000).toISOString()},{id:'u1',status:'Investigating',message:'On-call acknowledged elevated latency alerts.',author:'Elif Kaya',createdAtUtc:new Date(Date.now()-38*60000).toISOString()}]},
{id:'b',number:1041,title:'Intermittent Linux runner failures',summary:'A subset of builds fail during dependency restore.',severity:'Sev3',status:'Monitoring',commander:'Can Arslan',startedAtUtc:new Date(Date.now()-95*60000).toISOString(),slaDueAtUtc:new Date(Date.now()-5*60000).toISOString(),isSlaBreached:true,serviceName:'Build Runners',updates:[{id:'u3',status:'Monitoring',message:'Unhealthy runner pool drained. Success rate returned to baseline.',author:'Can Arslan',createdAtUtc:new Date(Date.now()-24*60000).toISOString()}]}]};

export default function IncidentPage({onBack}:{onBack:()=>void}){
 const [data,setData]=useState(seed),[selected,setSelected]=useState<Incident>(seed.incidents[0]),[modal,setModal]=useState(false);
 const [form,setForm]=useState({title:'',summary:'',severity:'Sev2' as IncidentSeverity,service:'Public API'});
 const countdown=useMemo(()=>Math.round((new Date(selected.slaDueAtUtc).getTime()-Date.now())/60000),[selected]);
 function create(){if(!form.title.trim())return; const item:Incident={id:crypto.randomUUID(),number:Math.max(...data.incidents.map(x=>x.number))+1,title:form.title,summary:form.summary,severity:form.severity,status:'Investigating',commander:'Yunus Emre',startedAtUtc:new Date().toISOString(),slaDueAtUtc:new Date(Date.now()+45*60000).toISOString(),isSlaBreached:false,serviceName:form.service,updates:[]};setData({...data,activeIncidents:data.activeIncidents+1,incidents:[item,...data.incidents]});setSelected(item);setModal(false)}
 return <main className="incident-shell"><header className="incident-top"><div><button className="ghost-back" onClick={onBack}><ArrowLeft size={16}/> Dashboard</button><small>OPERATIONS / INCIDENT COMMAND</small><h1>Incident Management</h1><p>Live service health, SLA response and post-incident coordination.</p></div><button className="declare" onClick={()=>setModal(true)}><ShieldAlert size={17}/> Declare incident</button></header>
 <section className="incident-kpis"><article><span><AlertTriangle/></span><div><small>ACTIVE INCIDENTS</small><strong>{data.activeIncidents}</strong><em>2 require attention</em></div></article><article><span><TimerReset/></span><div><small>MEAN TIME TO ACK</small><strong>{data.mttaMinutes}m</strong><em>↓ 18% this month</em></div></article><article><span><Clock3/></span><div><small>MEAN TIME TO RESOLVE</small><strong>{data.mttrMinutes}m</strong><em>Target under 60m</em></div></article><article><span><Gauge/></span><div><small>SLA COMPLIANCE</small><strong>{data.slaCompliancePercent}%</strong><em>30-day window</em></div></article></section>
 <section className="service-strip">{data.services.map(s=><article key={s.id}><span className={'service-dot '+s.status.toLowerCase()}></span><div><strong>{s.name}</strong><small>{s.description}</small></div><div className="service-stat"><b>{s.availabilityPercent}%</b><small>{s.status.replace(/([A-Z])/g,' $1')}</small></div></article>)}</section>
 <section className="incident-layout"><div className="incident-list"><header><div><h2>Active response</h2><p>Incidents ordered by severity and SLA risk.</p></div><Activity size={18}/></header>{data.incidents.map(i=><button key={i.id} className={'incident-row '+(selected.id===i.id?'selected':'')} onClick={()=>setSelected(i)}><span className={'severity '+i.severity.toLowerCase()}>{i.severity}</span><div><strong>#{i.number} · {i.title}</strong><small>{i.serviceName} · Commander: {i.commander}</small></div><span className={'incident-status '+i.status.toLowerCase()}>{i.status}</span><time>{Math.round((Date.now()-new Date(i.startedAtUtc).getTime())/60000)}m</time></button>)}</div>
 <aside className="incident-detail"><header><div><small>INC-{selected.number} · {selected.serviceName}</small><h2>{selected.title}</h2></div><span className={'severity '+selected.severity.toLowerCase()}>{selected.severity}</span></header><p>{selected.summary}</p><div className="sla-clock"><TimerReset/><div><small>SLA RESPONSE WINDOW</small><strong className={countdown<0?'late':''}>{countdown<0?`${Math.abs(countdown)}m overdue`:`${countdown}m remaining`}</strong></div></div><div className="incident-meta"><div><small>STATUS</small><b>{selected.status}</b></div><div><small>COMMANDER</small><b>{selected.commander}</b></div><div><small>STARTED</small><b>{new Date(selected.startedAtUtc).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</b></div></div><h3>Response timeline</h3><div className="timeline">{selected.updates.map(u=><article key={u.id}><span><CheckCircle2 size={15}/></span><div><strong>{u.status}</strong><p>{u.message}</p><small>{u.author} · {new Date(u.createdAtUtc).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</small></div></article>)}</div><button className="resolve"><CheckCircle2 size={16}/> Add response update</button></aside></section>
 {modal&&<div className="incident-modal-bg"><div className="incident-modal"><header><div><small>NEW RESPONSE</small><h2>Declare incident</h2></div><button onClick={()=>setModal(false)}><X/></button></header><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Describe the customer impact"/></label><label>Summary<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="What is happening and who is affected?"/></label><div className="modal-grid"><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value as IncidentSeverity})}><option>Sev1</option><option>Sev2</option><option>Sev3</option><option>Sev4</option></select></label><label>Service<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}>{data.services.map(s=><option key={s.id}>{s.name}</option>)}</select></label></div><button className="declare full" onClick={create}><Plus size={16}/> Start incident response</button></div></div>}</main>
}
