import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Boxes, GitBranch, Search, ShieldAlert, SlidersHorizontal, X } from 'lucide-react';
import { globalSearch, type SearchItem, type SearchResponse } from '../search';
const icon=(t:string)=>t==='project'?Boxes:t==='repository'?GitBranch:t==='incident'?ShieldAlert:t==='document'?BookOpen:SlidersHorizontal;
const fallback:SearchResponse={query:'',page:1,pageSize:20,total:6,elapsedMilliseconds:7,types:[{value:'work-item',count:2},{value:'project',count:1},{value:'repository',count:1},{value:'incident',count:1},{value:'document',count:1}],statuses:[{value:'active',count:2},{value:'inprogress',count:1},{value:'open',count:1},{value:'published',count:1},{value:'todo',count:1}],items:[
{id:'1',type:'work-item',title:'Add deployment rollback controls',subtitle:'Story · #284',status:'inprogress',reference:'#284',updatedAt:new Date().toISOString(),score:90,metadata:{priority:'High'}},
{id:'2',type:'project',title:'Platform Control Plane',subtitle:'Project PLT',status:'active',reference:'PLT',updatedAt:new Date().toISOString(),score:80,metadata:{}},
{id:'3',type:'repository',title:'control-plane-api',subtitle:'C# repository',status:'active',reference:'main',updatedAt:new Date().toISOString(),score:70,metadata:{language:'C#'}},
{id:'4',type:'incident',title:'Elevated authentication latency',subtitle:'Incident #91 · High',status:'open',reference:'INC-91',updatedAt:new Date().toISOString(),score:60,metadata:{severity:'High'}},
{id:'5',type:'document',title:'Production deployment runbook',subtitle:'Documentation · deployment-runbook',status:'published',reference:'deployment-runbook',updatedAt:new Date().toISOString(),score:55,metadata:{}},
{id:'6',type:'work-item',title:'Index global search records',subtitle:'Task · #301',status:'todo',reference:'#301',updatedAt:new Date().toISOString(),score:50,metadata:{priority:'Medium'}}]};
export default function SearchPage({onBack}:{onBack:()=>void}){const [q,setQ]=useState('');const [types,setTypes]=useState<string[]>([]);const [statuses,setStatuses]=useState<string[]>([]);const [sort,setSort]=useState('relevance');const [data,setData]=useState<SearchResponse>(fallback);const [loading,setLoading]=useState(false);
useEffect(()=>{const id=setTimeout(async()=>{setLoading(true);try{setData(await globalSearch(q,types,statuses,sort))}catch{const n=q.toLowerCase();setData({...fallback,query:q,items:fallback.items.filter(x=>!n||`${x.title} ${x.subtitle} ${x.reference}`.toLowerCase().includes(n)),total:fallback.items.filter(x=>!n||`${x.title} ${x.subtitle} ${x.reference}`.toLowerCase().includes(n)).length})}finally{setLoading(false)}},250);return()=>clearTimeout(id)},[q,types,statuses,sort]);
const toggle=(v:string,list:string[],set:(x:string[])=>void)=>set(list.includes(v)?list.filter(x=>x!==v):[...list,v]);const selected=types.length+statuses.length;const results=useMemo(()=>data.items,[data]);return <main className="search-shell"><header className="search-top"><button className="search-back" onClick={onBack}><ArrowLeft size={17}/>Overview</button><div><p className="eyebrow">Unified engineering index</p><h1>Global search</h1></div></header><section className="search-command"><Search size={21}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects, work items, repositories, incidents and docs…"/><kbd>⌘ K</kbd></section><div className="search-layout"><aside className="search-filters"><div className="filter-title"><SlidersHorizontal size={16}/><b>Filters</b>{selected>0&&<button onClick={()=>{setTypes([]);setStatuses([])}}>Clear</button>}</div><p>TYPE</p>{data.types.map(f=><label key={f.value}><input type="checkbox" checked={types.includes(f.value)} onChange={()=>toggle(f.value,types,setTypes)}/><span>{f.value.replace('-',' ')}</span><small>{f.count}</small></label>)}<p>STATUS</p>{data.statuses.slice(0,8).map(f=><label key={f.value}><input type="checkbox" checked={statuses.includes(f.value)} onChange={()=>toggle(f.value,statuses,setStatuses)}/><span>{f.value}</span><small>{f.count}</small></label>)}</aside><section className="search-results"><div className="result-toolbar"><span><b>{data.total}</b> results <small>in {data.elapsedMilliseconds} ms</small></span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Best match</option><option value="updated">Recently updated</option><option value="title">Title A–Z</option></select></div>{selected>0&&<div className="active-filters">{[...types,...statuses].map(x=><button key={x} onClick={()=>types.includes(x)?toggle(x,types,setTypes):toggle(x,statuses,setStatuses)}>{x}<X size={12}/></button>)}</div>}<div className={loading?'result-list is-loading':'result-list'}>{results.map((x:SearchItem)=>{const Icon=icon(x.type);return <article key={x.id} className="search-result"><div className={`result-icon type-${x.type}`}><Icon size={18}/></div><div className="result-main"><div><span className="result-type">{x.type}</span><span className={`result-status status-${x.status}`}>{x.status}</span></div><h3>{x.title}</h3><p>{x.subtitle}</p><footer><code>{x.reference}</code><span>Updated {new Date(x.updatedAt).toLocaleDateString('tr-TR')}</span>{Object.entries(x.metadata).slice(0,2).map(([k,v])=><span key={k}>{k}: {v}</span>)}</footer></div><span className="result-score">{Math.round(x.score)}%</span></article>})}{!results.length&&<div className="empty-search"><Search size={28}/><h2>No matching records</h2><p>Try a broader keyword or clear one of the active filters.</p></div>}</div></section></div></main>}
